In [1]:
import numpy as np

**Creating Arrays**

In [113]:
alpha = np.array([1,2,3], dtype=int)
beta = np.array([[1,2,3], [4,5,6]], dtype=np.int16)
ceta = np.zeros((3,4))
delta = np.ones((2,3,4))

print(alpha, end='\n\n')
print(beta, end='\n\n')
print(ceta, end='\n\n')
print(delta, end='\n\n')

[1 2 3]

[[1 2 3]
 [4 5 6]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]



In [114]:
alpha = np.arange(10, 25, 3)
beta = np.linspace(0,2,9)
ceta = np.full((2,2),7)
delta = np.eye(3)

print(alpha, end='\n\n')
print(beta, end='\n\n')
print(ceta, end='\n\n')
print(delta, end='\n\n')
print(np.identity(3), end='\n\n')
print(np.arange(16).reshape(2,4,2))

[10 13 16 19 22]

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]

[[7 7]
 [7 7]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]
  [12 13]
  [14 15]]]


In [115]:
alpha = np.random.random((2,2))
beta = np.random.rand(2,2)
ceta = np.random.randint(0, 10, (2,2))
delta = np.empty((3,2))

print(alpha, end='\n\n')
print(np.random.rand(), end='\n\n')
print(np.random.rand(5), end='\n\n')
print(beta, end='\n\n')
print(ceta, end='\n\n')
print(delta, end='\n\n')
print(np.random.uniform(0, 10, 5), end='\n\n')
print(np.round(alpha*100))

[[0.15383525 0.88963383]
 [0.58954176 0.80741018]]

0.42353532556963513

[0.15459381 0.22905443 0.24562887 0.02299168 0.09345264]

[[0.44128333 0.77562746]
 [0.41823939 0.09322452]]

[[3 3]
 [1 5]]

[[6.23042070e-307 1.33512376e-306]
 [1.11261230e-306 7.56577399e-307]
 [9.34600963e-307 5.56268465e-309]]

[9.19585487 6.53686543 3.85117403 2.25642368 3.49587618]

[[15. 89.]
 [59. 81.]]


**Random, linspace, Randint, Uniform, Arange**

In [136]:
random_float = np.random.random()
print(random_float, end='\n\n')
random_float = np.random.random(5)
print(random_float, end='\n\n')
random_float = np.random.random((3,3))
print(random_float, end='\n\n')
random_int = np.random.randint(1, 10, size=(3, 3))
print(random_int, end='\n\n')
random_uniform = np.random.uniform(0.0, 1.0, size=(3, 3))
print(random_uniform, end='\n\n')
array = np.arange(5)
print(array, end='\n\n')
array = np.arange(2, 10)
print(array, end='\n\n')
array = np.arange(2, 10, 3)
print(array, end='\n\n')

"""
    1. -- np.random.random() and np.random.uniform() both generate random floats, 
          but np.random.random() only generates floats in the range [0.0, 1.0) 
          while np.random.uniform() allows specifying a custom range.
    2. -- np.random.randint() generates random integers within a specified range.
    3. -- 
"""


0.8567890719752604

[0.44285002 0.2725018  0.8019581  0.94387948 0.602848  ]

[[0.21726727 0.84123462 0.95425116]
 [0.16406641 0.29253393 0.65822284]
 [0.40695503 0.66725438 0.87692383]]

[[2 5 7]
 [2 3 3]
 [7 1 2]]

[[0.536403   0.00995111 0.71196155]
 [0.57871692 0.73696846 0.20749627]
 [0.99704583 0.71104489 0.63363545]]

[0 1 2 3 4]

[2 3 4 5 6 7 8 9]

[2 5 8]



'\n    1. -- np.random.random() and np.random.uniform() both generate random floats, \n        but np.random.random() only generates floats in the range [0.0, 1.0) \n        while np.random.uniform() allows specifying a custom range.\n    2. -- np.random.randint() generates random integers within a specified range.\n    3. -- \n'

**Inspecting the Array**

In [116]:
print(alpha.shape)
print(len(alpha))
print(alpha.ndim)
print(alpha.size)
print(alpha.dtype)
print(alpha.dtype.name)
print(alpha.astype(float))

(2, 2)
2
2
4
float64
float64
[[0.15383525 0.88963383]
 [0.58954176 0.80741018]]


**Asking for Help**

In [117]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

.. warning::

    Setting ``arr.dtype`` is discouraged and may be deprecated in the
    future.  Setting will replace the ``dtype`` without modifying the
    memory (see also `ndarray.view` and `ndarray.astype`).

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
ndarray.astype : Cast the values contained in the array to a new data-type.
ndarray.view : Create a view of the same data but a different data-type.
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


**Array Mathematics**

In [118]:
print(np.shape(alpha), beta.shape)
print(alpha - beta)
print(np.subtract(alpha, beta))
print(alpha + beta)
print(np.add(beta, alpha))
print(alpha / beta)
print(np.divide(alpha, beta))
print(alpha * beta)
print(np.multiply(alpha, beta))
print(np.exp(alpha))
print(np.sqrt(alpha))
print(np.sin(alpha))
print(np.cos(alpha))
print(np.log(alpha))
print(alpha.dot(beta))

(2, 2) (2, 2)
[[-0.28744808  0.11400637]
 [ 0.17130238  0.71418566]]
[[-0.28744808  0.11400637]
 [ 0.17130238  0.71418566]]
[[0.59511859 1.66526129]
 [1.00778115 0.9006347 ]]
[[0.59511859 1.66526129]
 [1.00778115 0.9006347 ]]
[[0.3486088  1.14698599]
 [1.40957973 8.66092056]]
[[0.3486088  1.14698599]
 [1.40957973 8.66092056]]
[[0.06788493 0.69002443]
 [0.24656959 0.07527043]]
[[0.06788493 0.69002443]
 [0.24656959 0.07527043]]
[[1.16629873 2.43423814]
 [1.80316195 2.24209384]]
[[0.39221837 0.94320402]
 [0.76781623 0.89856006]]
[[0.15322921 0.77684122]
 [0.5559802  0.72249907]]
[[0.98819067 0.62969652]
 [0.83119554 0.69137189]]
[[-1.87187304 -0.11694533]
 [-0.52840972 -0.21392346]]
[[0.43996484 0.20225453]
 [0.59784569 0.53253521]]


**Comparison**

In [119]:
print(alpha == beta)
print(alpha < 3)
print(np.array_equal(alpha, beta))

[[False False]
 [False False]]
[[ True  True]
 [ True  True]]
False


**Aggregate Functions**

In [120]:
# axis = 0 => Row
# axis = 1 => Column
print(alpha.sum())
print(alpha.min())
print(alpha.max(axis=1))
print(alpha.cumsum(axis=0))
print(alpha.mean())
print(np.median(alpha))
print(np.corrcoef(alpha))
print(np.std(alpha))

2.4404210274006424
0.1538352523274943
[0.88963383 0.80741018]
[[0.15383525 0.88963383]
 [0.74337702 1.69704401]]
0.6101052568501606
0.6984759721771145
[[1. 1.]
 [1. 1.]]
0.2853377958932627


**Copying Arrays**

In [121]:
test = alpha.view()
print(test)
test = np.copy(alpha)
print(test)
test = alpha.copy()
print(test)

[[0.15383525 0.88963383]
 [0.58954176 0.80741018]]
[[0.15383525 0.88963383]
 [0.58954176 0.80741018]]
[[0.15383525 0.88963383]
 [0.58954176 0.80741018]]


**Sorting Arrays**

In [122]:
print(alpha.sort())
print(alpha.sort(axis=0))

None
None


**Subsetting**

In [100]:
print(alpha)
print(alpha[1])
print(alpha[1,1])

[[0.30149922 0.76616933]
 [0.59015872 0.90981225]]
[0.59015872 0.90981225]
0.9098122458961421


**Slicing**

In [124]:
alpha.reshape(2,2)
print(alpha, end='\n\n')
print(alpha[0:1], end='\n\n')
print(alpha[0:1, 1], end='\n\n')
print(alpha[:, 1], end='\n\n')
print(alpha[:1], end='\n\n')
print(alpha[1,...], end='\n\n')
print(alpha[::-1], end='\n\n')
test = np.random.randint(0, 10, (4,4))
print(test, end='\n\n')
# before first "," means row and after it means columns
print(test[::2,[0,1,3]])

[[0.15383525 0.80741018]
 [0.58954176 0.88963383]]

[[0.15383525 0.80741018]]

[0.80741018]

[0.80741018 0.88963383]

[[0.15383525 0.80741018]]

[0.58954176 0.88963383]

[[0.58954176 0.88963383]
 [0.15383525 0.80741018]]

[[4 3 5 6]
 [6 6 5 0]
 [7 2 7 1]
 [1 9 9 7]]

[[4 3 6]
 [7 2 1]]


**Boolean Indexing**

In [102]:
print(alpha[alpha<0.1])
print(alpha[alpha<1])

[]
[0.30149922 0.76616933 0.59015872 0.90981225]


**Transpoing Array**

In [103]:
test = np.transpose(alpha)
print(test)
print(alpha.T)

[[0.30149922 0.59015872]
 [0.76616933 0.90981225]]
[[0.30149922 0.59015872]
 [0.76616933 0.90981225]]


**Chaning Array Shape**

In [104]:
print(alpha.ravel()) # 1D
print(alpha.reshape(2,2))
print(alpha.reshape(-1)) # 1D

[0.30149922 0.76616933 0.59015872 0.90981225]
[[0.30149922 0.76616933]
 [0.59015872 0.90981225]]
[0.30149922 0.76616933 0.59015872 0.90981225]


**Adding / Removing Elements**

In [105]:
print(alpha.reshape(2,2))
# print(alpha.resize((4,1)))
print(np.append(alpha, beta))
print(np.insert(alpha, 1,5))
print(np.delete(alpha, [1]))

[[0.30149922 0.76616933]
 [0.59015872 0.90981225]]
[0.30149922 0.76616933 0.59015872 0.90981225 0.99862569 0.8444832
 0.70173981 0.33042652]
[0.30149922 5.         0.76616933 0.59015872 0.90981225]
[0.30149922 0.59015872 0.90981225]


**Combining Arrays**

In [106]:
print(alpha.reshape(2,2), beta.reshape(2,2))
# print(np.concatenate((alpha, beta), axis=0))
# print(np.vstack((alpha,beta)))
# print(np.r_[alpha, beta])
# print(np.hstack((alpha, beta)))
# print(np.column_stack((alpha, beta)))
# print(np.c_[alpha, beta])

[[0.30149922 0.76616933]
 [0.59015872 0.90981225]] [[0.99862569 0.8444832 ]
 [0.70173981 0.33042652]]


**Splitting Arrays**

In [107]:
# print(np.hsplit(alpha, 4))
# print(np.vsplit(alpha, 4))