### What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.


At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types

### Numpy Arrays Vs Python Sequences

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

In [2]:
# pip install numpy
import numpy as np

In [4]:
a = np.array([1,2,3,4,5,6,7,8,9], dtype=float)
print(a)
# a
# type(a)

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [5]:
b = np.array([[1,2,3,4],[5,6,7,8,]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [7]:
c = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [18]:
d = np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]], dtype=float)
d

array([[[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.]],

        [[ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[13., 14., 15.],
         [16., 17., 18.]]]])

In [11]:
np.shape(d)

(1, 3, 2, 3)

In [19]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [20]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [6]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [12]:
np.arange(1,11.5)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [11]:
np.arange(1.5,11.5)

array([ 1.5,  2.5,  3.5,  4.5,  5.5,  6.5,  7.5,  8.5,  9.5, 10.5])

In [9]:
np.arange('a','z')

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [24]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [29]:
np.arange(18).reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [30]:
# The outermost dimension will have 3 arrays that contains 6 arrays, each with 1 element
np.arange(18).reshape(3,6,1)

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]],

       [[12],
        [13],
        [14],
        [15],
        [16],
        [17]]])

Unknown Dimension
You are allowed to have one "unknown" dimension.

Meaning that you do not have to specify an exact number for one of the dimensions in the reshape method.

Pass -1 as the value, and NumPy will calculate this number for you.

In [34]:
np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]).reshape(4,2,-1)


array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

Convert a multidimensional arrayinto 1D

In [37]:
a = np.arange(18).reshape(3,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [38]:
a.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [39]:
type(a)

numpy.ndarray

In [41]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
a = np.random.random((3,4))
a

array([[0.7588824 , 0.42258643, 0.53008741, 0.73883692],
       [0.43981874, 0.80210883, 0.89184761, 0.90703401],
       [0.50981221, 0.46987098, 0.89497335, 0.22834047]])

In [48]:
a*100

array([[75.88824013, 42.25864311, 53.00874119, 73.88369195],
       [43.98187374, 80.21088252, 89.1847605 , 90.70340139],
       [50.98122074, 46.98709806, 89.49733496, 22.83404716]])

In [ ]:
numpy.linspace(start,
               stop,
               num = 50,
               endpoint = True,
               retstep = False,
               dtype = None)

In [54]:
np.linspace(1,90,25,dtype=str)

array(['1.0', '4.708333333333334', '8.416666666666668', '12.125',
       '15.833333333333334', '19.541666666666668', '23.25',
       '26.958333333333336', '30.666666666666668', '34.375',
       '38.083333333333336', '41.79166666666667', '45.5',
       '49.208333333333336', '52.91666666666667', '56.625',
       '60.333333333333336', '64.04166666666667', '67.75',
       '71.45833333333334', '75.16666666666667', '78.875',
       '82.58333333333334', '86.29166666666667', '90.0'], dtype='<U32')

In [59]:
np.identity(8)

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [60]:
np.identity(8).reshape(2,2,2,8)

array([[[[1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1.]]]])

In [64]:
import sys

In [67]:
a1 = np.arange(10,dtype=np.int64)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

sys.getsizeof(a1)

192

In [70]:
a2 = np.arange(12,dtype=np.float64).reshape(3,4)
sys.getsizeof(a2)

128

In [71]:
a3.ndim

3

In [76]:
print(a3.shape)
a3

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [77]:
a3.size

8

In [78]:
a3.itemsize

4

In [80]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int32


In [89]:
# will change the size temporary
# a2.astype(np.float32)
# will change the size permanently
a2 = a2.astype(np.float32)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]], dtype=float32)

In [90]:
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float32
int32


In [97]:
np.arange(10,46,3).reshape(2,6)

array([[10, 13, 16, 19, 22, 25],
       [28, 31, 34, 37, 40, 43]])

In [101]:
a1 = np.arange(12).reshape(2,2,3)
a1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [102]:
a1 * 2

array([[[ 0,  2,  4],
        [ 6,  8, 10]],

       [[12, 14, 16],
        [18, 20, 22]]])

In [108]:
a1 == 5

array([[[False, False, False],
        [False, False,  True]],

       [[False, False, False],
        [False, False, False]]])

In [110]:
a1

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [121]:
a2 = a2.reshape(2,2,-1)

In [122]:
a1 * a2

array([[[  0.,   1.,   4.],
        [  9.,  16.,  25.]],

       [[ 36.,  49.,  64.],
        [ 81., 100., 121.]]])

In [135]:
a1 = np.random.random((3,4))
a1 = np.round(a1*100)
a1 = a1.astype(int)
a1

array([[40, 13, 93, 46],
       [16, 80, 76, 45],
       [89, 54, 53,  2]])

In [136]:
# max/min/sum/prod
# 0 -> col and 1 -> row
np.max(a1,axis=0)

array([89, 80, 93, 46])

In [143]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

In [144]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
a3

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [146]:
np.dot(a2,a3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [147]:
# round/floor/ceil

np.ceil(np.random.random((2,3))*100)

array([[99., 53., 63.],
       [46., 82., 94.]])

In [148]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[70., 68., 27.],
       [90., 38., 73.]])

In [149]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [151]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [154]:
a2[1][0]

4

In [153]:
a2[1,0]

4

In [157]:
a3[0]

array([[0, 1],
       [2, 3]])

In [158]:
a3[0,1]

array([2, 3])

In [159]:
a3[0,1,0]

2

In [160]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [161]:
a1[2:5:2]

array([2, 4])

In [162]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [188]:
a2[::2]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11]])

In [189]:
a2[::2,::2]

array([[ 0,  2],
       [ 8, 10]])

In [175]:
a2[::,:1:1]

array([[0],
       [4],
       [8]])

In [176]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [190]:
a3[::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [191]:
a3[::,::2]

array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [15, 16, 17]],

       [[18, 19, 20],
        [24, 25, 26]]])

In [194]:
a3[::,::2,::2]

array([[[ 0,  2],
        [ 6,  8]],

       [[ 9, 11],
        [15, 17]],

       [[18, 20],
        [24, 26]]])

In [195]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [196]:
a3[::]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [199]:
a3[::,2::3]

array([[[ 6,  7,  8]],

       [[15, 16, 17]],

       [[24, 25, 26]]])

In [203]:
a3[::,2::3, 1]

array([[ 7],
       [16],
       [25]])

In [204]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [207]:
a3[1,:,1]

array([10, 13, 16])

In [208]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [209]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [210]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [212]:
for i in a2:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11


In [213]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [215]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [216]:
for i in a3:
    for j in i:
        print(j)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]
[12 13 14]
[15 16 17]
[18 19 20]
[21 22 23]
[24 25 26]


In [225]:
# this process cause a lot of computation power because of loops
l = 0
for i in a3:
    for j in i:
        for k in j:
            print(k)
            # l = l + 1
            

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [226]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


In [230]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [228]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [231]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [232]:
a3.reshape(-1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [233]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [234]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [236]:
# horizontal stacking
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [237]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [240]:
a3 = np.hstack((a1,a2))
a3

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [241]:
a4 = np.vstack((a1,a2))
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [244]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]]),
 array([[16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [246]:
np.hsplit(a4,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13],
        [16, 17],
        [20, 21]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15],
        [18, 19],
        [22, 23]])]