In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataPath = '/titanic.csv'
df = pd.read_csv(dataPath)
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [ ]:
df.drop(columns=['PassengerId', 'Name', 'Ticket', 'Cabin'], axis = 1, inplace = True)
df.head(5)

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0         0       3    male  22.0      1      0   7.2500        S
1         1       1  female  38.0      1      0  71.2833        C
2         1       3  female  26.0      0      0   7.9250        S
3         1       1  female  35.0      1      0  53.1000        S
4         0       3    male  35.0      0      0   8.0500        S

In [ ]:
from sklearn.model_selection import train_test_split, GridSearchCV

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(columns=['Survived']), df['Survived'], test_size = 0.2, random_state = 42)

In [ ]:
X_train[:2]

Pclass   Sex   Age  SibSp  Parch  Fare Embarked
331       1  male  45.5      0      0  28.5        S
733       2  male  23.0      0      0  13.0        S

In [ ]:
X_test[:2]

Pclass   Sex   Age  SibSp  Parch     Fare Embarked
709       3  male   NaN      1      1  15.2458        C
439       2  male  31.0      0      0  10.5000        S

In [ ]:
y_train[:2]

331    0
733    0
Name: Survived, dtype: int64

In [ ]:
y_test[:2]

709    1
439    0
Name: Survived, dtype: int64

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

In [ ]:
from sklearn import tree
import matplotlib.pyplot as plt

In [ ]:
transformer1 = ColumnTransformer([
    ('impute_age', SimpleImputer(), [2]),
    ('impute_embarked', SimpleImputer(strategy = 'most_frequent'), [6]),
], remainder='passthrough')

transformer2 = ColumnTransformer([
    ('ohe_sex_embarked', OneHotEncoder(sparse_output=False, handle_unknown='ignore'), [1, 6])
])

# transformer3 = ColumnTransformer([
#     ('scale', MinMaxScaler(), slice(0, 10))
# ])

transformer4 = ColumnTransformer([
    ('standard_scale', StandardScaler(), slice(0, 10))
])

In [ ]:
param_grid = {
    'C': [0.1, 1, 10],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto', 0.1, 1],
}

# Create a grid search object
svm_classifier = SVC()
transformer5 = GridSearchCV(svm_classifier, param_grid, cv=5)

In [ ]:
transformer6 = LogisticRegression()

In [ ]:
transformer7 = DecisionTreeClassifier()

In [ ]:
transformer8 = CountVectorizer()

In [ ]:
transformer9 = RandomForestClassifier(n_estimators=100, random_state=42)

In [ ]:
from sklearn.pipeline import Pipeline

In [ ]:
pipeSVC = Pipeline([
    ('Transformer1', transformer1),
    ('Transformer2', transformer2),
    # ('Transformer3', transformer3),
    ('Transformer4', transformer4),
    ('Transformer5', transformer5),
])

In [ ]:
pipeLogistic = Pipeline([
    ('Transformer1', transformer1),
    ('Transformer2', transformer2),
    # ('Transformer3', transformer3),
    ('Transformer4', transformer4),
    ('Transformer6', transformer6),
])

In [ ]:
pipeDecision = Pipeline([
    ('Transformer1', transformer1),
    ('Transformer2', transformer2),
    # ('Transformer3', transformer3),
    ('Transformer4', transformer4),
    ('Transformer7', transformer7),
])

In [ ]:
pipeNaive = Pipeline([
    ('Transformer1', transformer1),
    ('Transformer2', transformer2),
    # ('Transformer3', transformer3),
    ('Transformer4', transformer4),
    ('Transformer8', transformer8),
])

In [ ]:
pipeRandom = Pipeline([
    ('Transformer1', transformer1),
    ('Transformer2', transformer2),
    # ('Transformer3', transformer3),
    ('Transformer4', transformer4),
    ('Transformer9', transformer9),
])

## SVC model

In [ ]:
pipeSVC.fit(X_train, y_train)

Pipeline(steps=[('Transformer1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('Transformer2',
                 ColumnTransformer(transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('Transformer4',
                 ColumnTransformer(transformers=[('standard_scale',
                                                  StandardScaler(),
                                                  slice(0, 10, None))])),
                ('Transformer5',
                 GridSearchCV(cv=5, estimator=SVC(),
                              param_grid={'C': [0.1, 1, 10],
                                          'gamma': ['scale', 'auto', 0.1, 1],
                                          'kernel': ['linear', 'rbf',
                                                     'poly']}))])

In [ ]:
y_predSVC = pipeSVC.predict(X_test)
y_predSVC

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0], dtype=int64)

In [ ]:
# Evaluate the classifier
accuracy = accuracy_score(y_test, y_predSVC)
confusion = confusion_matrix(y_test, y_predSVC)
classification_rep = classification_report(y_test, y_predSVC)

# Print the evaluation metrics
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", classification_rep)

Accuracy: 0.6256983240223464
Confusion Matrix:
 [[87 18]
 [49 25]]
Classification Report:
               precision    recall  f1-score   support

           0       0.64      0.83      0.72       105
           1       0.58      0.34      0.43        74

    accuracy                           0.63       179
   macro avg       0.61      0.58      0.57       179
weighted avg       0.62      0.63      0.60       179



## Logistic regression

In [ ]:
pipeLogistic.fit(X_train, y_train)

Pipeline(steps=[('Transformer1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('Transformer2',
                 ColumnTransformer(transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('Transformer4',
                 ColumnTransformer(transformers=[('standard_scale',
                                                  StandardScaler(),
                                                  slice(0, 10, None))])),
                ('Transformer6', LogisticRegression())])

In [ ]:
y_predLogistic = pipeLogistic.predict(X_test)
y_predLogistic

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0], dtype=int64)

In [ ]:
accuracy = accuracy_score(y_test, y_predLogistic)
confusion = confusion_matrix(y_test, y_predLogistic)
classification_rep = classification_report(y_test, y_predLogistic)

# Print the evaluation metrics
print("Accuracy:", accuracy)
print("Confusion Matrix:\n", confusion)
print("Classification Report:\n", classification_rep)

Accuracy: 0.6256983240223464
Confusion Matrix:
 [[87 18]
 [49 25]]
Classification Report:
               precision    recall  f1-score   support

           0       0.64      0.83      0.72       105
           1       0.58      0.34      0.43        74

    accuracy                           0.63       179
   macro avg       0.61      0.58      0.57       179
weighted avg       0.62      0.63      0.60       179



## Decision Tree

In [ ]:
pipeDecision.fit(X_train, y_train)

Pipeline(steps=[('Transformer1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('Transformer2',
                 ColumnTransformer(transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('Transformer4',
                 ColumnTransformer(transformers=[('standard_scale',
                                                  StandardScaler(),
                                                  slice(0, 10, None))])),
                ('Transformer7', DecisionTreeClassifier())])

In [ ]:
y_predDecision = pipeDecision.predict(X_test)
y_predDecision

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0], dtype=int64)

In [ ]:
pipeDecision.score(X_train, y_train)

0.6418539325842697

In [ ]:
# tree.plot_tree(pipeDecision, feature_names=None, class_names=None, filled=True)
# plt.show()

## Naive Bayes

In [ ]:
# pipeNaive.fit(X_train, y_train)

In [ ]:
# y_predNaive = pipeNaive.predict(X_test)
# y_predNaive

In [ ]:
# y_predNaive.score(X_train, y_train)

## Random Forest

In [ ]:
pipeRandom.fit(X_train, y_train)

Pipeline(steps=[('Transformer1',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('impute_age', SimpleImputer(),
                                                  [2]),
                                                 ('impute_embarked',
                                                  SimpleImputer(strategy='most_frequent'),
                                                  [6])])),
                ('Transformer2',
                 ColumnTransformer(transformers=[('ohe_sex_embarked',
                                                  OneHotEncoder(handle_unknown='ignore',
                                                                sparse_output=False),
                                                  [1, 6])])),
                ('Transformer4',
                 ColumnTransformer(transformers=[('standard_scale',
                                                  StandardScaler(),
                                                  slice(0, 10, None))])),
                ('Transformer9', RandomForestClassifier(random_state=42))])

In [ ]:
y_predRandom = pipeRandom.predict(X_test)
y_predRandom

array([1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0], dtype=int64)

In [ ]:
pipeRandom.score(X_train, y_train)

0.6418539325842697