In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.DataFrame({'text':['People likes me', 'People loves me', 'People do not like me', 'I like people'], 'output': [1,1,0,0]})
df

text  output
0        People likes me       1
1        People loves me       1
2  People do not like me       0
3          I like people       0

**Bag Of Words**

In [6]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [7]:
bow = cv.fit_transform(df['text'])

In [19]:
cv.vocabulary_ #index positions like people: 6

{'people': 6, 'likes': 2, 'me': 4, 'loves': 3, 'do': 0, 'not': 5, 'like': 1}

In [20]:
bow[0].toarray()

array([[0, 0, 1, 0, 1, 0, 1]], dtype=int64)

In [21]:
bow[1].toarray()

array([[0, 0, 0, 1, 1, 0, 1]], dtype=int64)

In [25]:
cv.transform(['Hey! People likes me alot and I love people alot people People']).toarray()

array([[0, 0, 1, 0, 1, 0, 4]], dtype=int64)

In [26]:
df = pd.DataFrame({'text':['People likes me', 'People loves me', 'People do not like me', 'I like people'], 'output': [1,1,0,0]})
df

text  output
0        People likes me       1
1        People loves me       1
2  People do not like me       0
3          I like people       0

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [30]:
tfidf.fit_transform(df['text']).toarray()

array([[0.        , 0.        , 0.77157901, 0.        , 0.49248889,
        0.        , 0.40264194],
       [0.        , 0.        , 0.        , 0.77157901, 0.49248889,
        0.        , 0.40264194],
       [0.55037169, 0.43391936, 0.        , 0.        , 0.35129512,
        0.55037169, 0.28720678],
       [0.        , 0.83388421, 0.        , 0.        , 0.        ,
        0.        , 0.55193942]])

In [33]:
print(tfidf.idf_)
print(tfidf.get_feature_names_out())

[1.91629073 1.51082562 1.91629073 1.91629073 1.22314355 1.91629073
 1.        ]
['do' 'like' 'likes' 'loves' 'me' 'not' 'people']
