In [1]:
import numpy as np
import pandas as pd
import gensim
import os

In [2]:
from nltk import sent_tokenize, word_tokenize
from gensim.utils import simple_preprocess

complete_story = []

for filename in os.listdir('Datasets/GOT'):
    # file = open(os.path.join('Datasets/GOT', filename), 'r')
    file = open('Datasets/GOT/' + filename, 'r')
    corpus = file.read()
    # print(corpus)
    raw_sentences = sent_tokenize(corpus)
    for sentence in raw_sentences:
        complete_story.append(simple_preprocess(sentence))

In [3]:
print(complete_story[0])
print(len(complete_story))

['game', 'of', 'thrones', 'book', 'one', 'of', 'song', 'of', 'ice', 'and', 'fire', 'by', 'george', 'martin', 'prologue', 'we', 'should', 'start', 'back', 'gared', 'urged', 'as', 'the', 'woods', 'began', 'to', 'grow', 'dark', 'around', 'them']
145020


In [4]:
complete_story

[['game',
  'of',
  'thrones',
  'book',
  'one',
  'of',
  'song',
  'of',
  'ice',
  'and',
  'fire',
  'by',
  'george',
  'martin',
  'prologue',
  'we',
  'should',
  'start',
  'back',
  'gared',
  'urged',
  'as',
  'the',
  'woods',
  'began',
  'to',
  'grow',
  'dark',
  'around',
  'them'],
 ['the', 'wildlings', 'are', 'dead'],
 ['do', 'the', 'dead', 'frighten', 'you'],
 ['ser',
  'waymar',
  'royce',
  'asked',
  'with',
  'just',
  'the',
  'hint',
  'of',
  'smile'],
 ['gared', 'did', 'not', 'rise', 'to', 'the', 'bait'],
 ['he',
  'was',
  'an',
  'old',
  'man',
  'past',
  'fifty',
  'and',
  'he',
  'had',
  'seen',
  'the',
  'lordlings',
  'come',
  'and',
  'go'],
 ['dead', 'is', 'dead', 'he', 'said'],
 ['we', 'have', 'no', 'business', 'with', 'the', 'dead'],
 ['are', 'they', 'dead'],
 ['royce', 'asked', 'softly'],
 ['what', 'proof', 'have', 'we'],
 ['will', 'saw', 'them', 'gared', 'said'],
 ['if',
  'he',
  'says',
  'they',
  'are',
  'dead',
  'that',
  'proof',


In [5]:
model = gensim.models.Word2Vec(
    window = 10, # 2 side 10, 10 words 
    min_count = 2, # minimum number of sentece to be taken
    workers = 10, # Number of CPUs
    vector_size = 100 # Number of features
)

In [6]:
model.build_vocab(complete_story)

In [7]:
model.train(complete_story, total_examples = model.corpus_count, epochs = 10)

(13141041, 17256380)

In [8]:
model.wv.most_similar('daenerys')

[('stormborn', 0.7430004477500916),
 ('targaryen', 0.6740061640739441),
 ('viserys', 0.6332933902740479),
 ('dragons', 0.6037667393684387),
 ('unburnt', 0.5754110813140869),
 ('aegon', 0.5657469630241394),
 ('dragon', 0.5656591653823853),
 ('elia', 0.5618458390235901),
 ('myrcella', 0.5444357395172119),
 ('queen', 0.5438950061798096)]

In [9]:
model.wv.doesnt_match(['daener', 'john', 'robb', 'arya'])

'john'

In [10]:
print(model.wv['john'].shape)
model.wv['john']

(100,)


array([ 0.07284582,  0.03695839,  0.08356304, -0.08147812, -0.09598588,
       -0.20106153,  0.02468834,  0.2333385 , -0.12708104,  0.02833782,
       -0.01401475, -0.14313127, -0.06714913,  0.00800303,  0.06703705,
       -0.07089881,  0.13700101, -0.11801047, -0.16686618, -0.14276686,
        0.03875004, -0.01785251,  0.10632333, -0.04945896, -0.12860028,
        0.03926179, -0.10697932, -0.02055888, -0.12028715,  0.02155583,
       -0.0934751 ,  0.00787016,  0.09618429, -0.10731526, -0.04748499,
        0.17230925,  0.04352207, -0.04597435, -0.0994973 , -0.19866621,
       -0.01513372,  0.02276882, -0.00751465,  0.00197751,  0.20676279,
       -0.05990925,  0.06884968, -0.03118551,  0.04225772,  0.12910865,
       -0.01088502,  0.02881214,  0.02935446,  0.05427846, -0.00990791,
        0.03422395,  0.16133527, -0.05811173, -0.20039162,  0.18611497,
       -0.03299946,  0.12124228,  0.05615389,  0.04247983, -0.03143842,
        0.01555304, -0.07402476,  0.04621349, -0.12373647,  0.07

In [11]:
model.wv.similarity('arya', 'sansa')

0.79545677

In [12]:
model.wv.similarity('tywin', 'sansa')

0.23479165

In [13]:
print(model.wv.get_normed_vectors().shape)
model.wv.get_normed_vectors()

(17453, 100)


array([[-0.1724635 , -0.12374561,  0.12398213, ..., -0.00616753,
        -0.09255906,  0.20335485],
       [-0.19262342, -0.15315329,  0.13814068, ..., -0.08975472,
         0.03858978, -0.01327871],
       [ 0.14544171, -0.06291664, -0.00530583, ..., -0.03260806,
         0.01831827, -0.06220768],
       ...,
       [ 0.0785265 ,  0.06303919, -0.08843918, ..., -0.08188722,
         0.08299837, -0.15624501],
       [-0.0953998 ,  0.07588639,  0.08699083, ..., -0.12087574,
         0.13173696, -0.13466156],
       [-0.08836133,  0.08531455,  0.06830281, ..., -0.02184378,
         0.04483509,  0.00102878]], dtype=float32)

In [14]:
print(len(model.wv.index_to_key))
model.wv.index_to_key

17453


['the',
 'and',
 'to',
 'of',
 'he',
 'his',
 'was',
 'you',
 'her',
 'in',
 'it',
 'had',
 'that',
 'she',
 'as',
 'with',
 'him',
 'not',
 'but',
 'for',
 'they',
 'is',
 'at',
 'on',
 'said',
 'my',
 'have',
 'be',
 'lord',
 'them',
 'no',
 'from',
 'would',
 'were',
 'me',
 'your',
 'one',
 'all',
 'when',
 'will',
 'ser',
 'if',
 'so',
 'their',
 'we',
 'could',
 'are',
 'man',
 'there',
 'this',
 'up',
 'been',
 'what',
 'did',
 'by',
 'king',
 'do',
 'men',
 'back',
 'out',
 'more',
 'or',
 'who',
 'down',
 'well',
 'than',
 'only',
 'like',
 'jon',
 'some',
 'father',
 'old',
 'hand',
 'even',
 'too',
 'tyrion',
 'before',
 'never',
 'an',
 'off',
 'see',
 'know',
 'into',
 'made',
 'now',
 'eyes',
 'black',
 'told',
 'lady',
 'thought',
 'time',
 'then',
 'how',
 'long',
 'has',
 'can',
 'might',
 'us',
 'come',
 'where',
 'here',
 'through',
 'still',
 'face',
 'head',
 'red',
 'll',
 'way',
 'boy',
 'page',
 'must',
 'once',
 'queen',
 'good',
 'two',
 'brother',
 'night',
 

In [26]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)

In [27]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [28]:
print(X.shape)
X[:5]

(17453, 3)


array([[ 0.28142893,  0.3856626 , -0.07390698],
       [ 0.23866548,  0.19695002,  0.00196815],
       [-0.09325378,  0.5745543 ,  0.09548307],
       [ 0.04948292,  0.21670614, -0.06279664],
       [ 0.077223  ,  0.47010008,  0.1546423 ]], dtype=float32)

In [20]:
import plotly.express as plt
fig = plt.scatter_3d(X[:500], x = 0, y = 1, z = 2, color = model.wv.index_to_key[:500])

In [21]:
fig.show()

In [44]:
X = X[:, :2]
plt.scatter(X[:, 0], X[:, 1])