In [365]:
import numpy as np
import math
import time
import random
import sympy #pip install sympy

Reshaping arrays with NumPy

a) Create a function that takes a NumPy array of shape (length,width,height) and converts it in to a
vector of shape (length*width*height,1). Use the function array.reshape() for this

In [3]:
a = np.arange(0, 16).reshape(2,4,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]]])

In [6]:
a.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15]])

 Building a basic mathematical function with NumPy:

a) Write a function that returns the sigmoid of a real number x. Use math.exp(x) for the exponential
function. Sigmoid(x)=1/(1+exp(-x))

In [16]:
def calculateSigmoid (number):
    return 1/(1 + math.exp(-number))

number = float(input("Enter the number: "))
print(calculateSigmoid(number))

0.7310585786300049


b) Now create a list of 5 values and call your sigmoid function with the list as input. You will get an
error because math.exp() only works when input is a real number. It does not work with vectors
and matrices. Now create a new function for sigmoid but this time use np.exp() instead of
math.exp(). Np.exp() works with all types of inputs including real numbers, vectors and matrices.
In deep learning we mostly use matrices and vectors. This is why NumPy is more useful. Call your
new function with a vector created by np.array() function

In [ ]:
a = np.array([2,3,4,8,1,7])
calculateSigmoid(a)


In [21]:
def calculateSigmoid (number):
    return 1/(1 + np.exp(-number))

In [22]:
print(calculateSigmoid(a))

[0.88079708 0.95257413 0.98201379 0.99966465 0.73105858 0.99908895]


Normalizing matrices with NumPy

Create a function that takes a NumPy matrix as input and returns the normalized by row NumPy
matrix. Check if your function is working correctly by using suitable inputs.

In [76]:
def normalized (matrix):

    sum = np.sum(matrix, 1)
    print(sum, '\n')
    normalizedMatrix = matrix/sum.reshape(-1,1)
    return np.round(normalizedMatrix, 2)

    # these two words same, newaxis create new axis at the given position "arr[:, np.newaxis, :].shape"
    # print(sum.reshape(-1,1))
    # print(sum[:, np.newaxis])
    

In [77]:
a = np.arange(0,16).reshape(4,4)
print(a,'\n')
print(normalized(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[ 6 22 38 54] 

[[0.   0.17 0.33 0.5 ]
 [0.18 0.23 0.27 0.32]
 [0.21 0.24 0.26 0.29]
 [0.22 0.24 0.26 0.28]]


Implementing a function on a matrix:

Create a function that takes a matrix as input and returns the softmax (by row) of matrix. The softmax
function is defined like this:
𝑠𝑜𝑓𝑡𝑚𝑎𝑥(𝒙) = 𝑠𝑜𝑓𝑡𝑚𝑎𝑥([𝑥1 𝑥2 … 𝑥𝑛]) = [
𝑒𝑥1
∑𝑗 𝑒𝑥𝑗
𝑒𝑥2
∑𝑗 𝑒𝑥𝑗 …
𝑒𝑥𝑛
∑𝑗 𝑒𝑥𝑗]
Check if your function is working correctly by using suitable inputs

In [117]:
def calculateSoftmax(matrix):

    expo = np.exp(matrix)
    sum = np.sum(expo, 1)
    softmatrix = matrix/sum
    return softmatrix


In [118]:
a = np.arange(0,16).reshape(4,4)
print(a,'\n')
print(calculateSoftmax(a))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[0.00000000e+00 5.87173801e-04 2.15089266e-05 5.90924599e-07]
 [1.28234413e-01 2.93586900e-03 6.45267798e-05 1.37882406e-06]
 [2.56468826e-01 5.28456421e-03 1.07544633e-04 2.16672353e-06]
 [3.84703239e-01 7.63325941e-03 1.50562486e-04 2.95462299e-06]]


5: Finding dot product using NumPy:

a) Create a function that implements dot product of two vectors. The input to the function should
be two standard python lists. Identify the time taken to evaluate the dot product using a
particular example of your choice

In [155]:
def calculateDotProduct (vector1, vector2):
    dotProductValue = 0
    for i in range(10):
        product = vector1[i] * vector2[i]
        dotProductValue = dotProductValue + product
    return dotProductValue


vector1 = [random.randint(0, 1000000) for _ in range(100000)]
vector2 = [random.randint(0, 1000000) for _ in range(100000)]

# print(vector1)
# print(vector2, '\n')


startTime = time.time()
dotProductValue = calculateDotProduct(vector1, vector2)
endTime = time.time()
totalTime = endTime - startTime

print(f'Dot product is: {dotProductValue},\n and total time is: {totalTime},\n strat time is: {startTime},\n and end time is: {endTime}')

Dot product is: 1981674965319,
 and total time is: 0.0,
 strat time is: 1695139319.2673278,
 and end time is: 1695139319.2673278


b) Now create another function that implements dot product of two vectors using np.dot() function.
Identify the time taken to evaluate this dot product and compare it with the time taken in part
a

In [154]:
vector1 = np.arange(0, 100, 10)
vector2 = np.arange(0, 100, 10)

start = time.time()

dotProductValue = vector1.dot(vector2)
end = time.time()

print(f'start time is: {start},\n and end time is {end},\n and total time is: {end-start},\n and dot product is: {dotProductValue}')



start time is: 1695139296.8215709,
 and end time is 1695139296.8215709,
 and total time is: 0.0,
 and dot product is: 28500


6:  Finding outer product using NumPy

If u and v are column vectors with the same size, then uT v is the inner product of u and v; if u and v are column vectors of any size, then uvT is the outer product of u and v.

a) Create a function that implements outer product of two vectors. The input to the function should
be two standard python lists. Identify the time taken to evaluate the outer product using a
particular example of your choice.

In [163]:
def calculateDotProduct (vector1, vector2):
    dotProductValue = 0
    for i in range(10):
        product = vector1[i] * vector2[i]
        dotProductValue = dotProductValue + product
    return dotProductValue


vector1 = [random.randint(0, 1000000) for _ in range(100000)]
vector2 = [random.randint(0, 1000000) for _ in range(100000)]

# print(vector1)
# print(vector2, '\n')


startTime = time.time()
dotProductValue = calculateDotProduct(vector1, vector2)
endTime = time.time()
totalTime = endTime - startTime

print(f'Dot product is: {dotProductValue},\n and total time is: {totalTime},\n strat time is: {startTime},\n and end time is: {endTime}')

Dot product is: 2573344486199,
 and total time is: 0.0,
 strat time is: 1695140183.16291,
 and end time is: 1695140183.16291


b) Now create another function that implements outer product of two vectors using np.outer()
function. Identify the time taken to evaluate this dot product and compare it with the time taken
in part a

In [177]:
vector1 = np.arange(0, 100, 10).reshape(-1,1)
vector2 = np.arange(0, 100, 10).reshape(-1,1)

print(vector1.shape)
start = time.time()

dotProductValue = np.outer(vector1, vector2)
end = time.time()

print(f'start time is: {start},\n and end time is {end},\n and total time is: {end-start},\n and dot product is: {dotProductValue}')



(10, 1)
start time is: 1695140644.103041,
 and end time is 1695140644.103041,
 and total time is: 0.0,
 and dot product is: [[   0    0    0    0    0    0    0    0    0    0]
 [   0  100  200  300  400  500  600  700  800  900]
 [   0  200  400  600  800 1000 1200 1400 1600 1800]
 [   0  300  600  900 1200 1500 1800 2100 2400 2700]
 [   0  400  800 1200 1600 2000 2400 2800 3200 3600]
 [   0  500 1000 1500 2000 2500 3000 3500 4000 4500]
 [   0  600 1200 1800 2400 3000 3600 4200 4800 5400]
 [   0  700 1400 2100 2800 3500 4200 4900 5600 6300]
 [   0  800 1600 2400 3200 4000 4800 5600 6400 7200]
 [   0  900 1800 2700 3600 4500 5400 6300 7200 8100]]


7: Defining Loss Functions:

a) Create a function that takes two vectors in the form of standard python lists and returns the L1
loss according to the above formula.:

In [179]:
def calculateL1Loss (vector1, vector2):
    loss = 0
    for i in range(len(vector1)):
        ls = vector1[i] - vector2[i]
        loss = loss + ls
    return loss/len(vector1)

vector1 = [random.randint(0, 100) for _ in range(10)]
vector2 = [random.randint(0, 100) for _ in range(10)]

print(vector1)
print(vector2)

print(f"Loss is: {calculateL1Loss(vector1, vector2)}")

[44, 18, 55, 99, 43, 77, 81, 57, 59, 55]
[79, 60, 15, 18, 63, 1, 5, 65, 44, 5]
Loss is: 23.3


b)  Now create another function that returns L1 loss but uses NumPy arrays instead of standard
python list. Compare the two approaches.

In [182]:
def calculateL1Loss (vector1, vector2):
    loss = 0
    for i in range(len(vector1)):
        ls = vector1[i] - vector2[i]
        loss = loss + ls
    return loss/len(vector1)

vector1 = np.random.randint(0, 100, 10)
vector2 = np.random.randint(0, 100, 10)

print(vector1)
print(vector2)

print(f"Loss is: {calculateL1Loss(vector1, vector2)}")

[59 16 15 59 77 73 34 21 86 14]
[74 76 78 11 64 67 99 16 11 45]
Loss is: -8.7


c) Create a function that takes two vectors in the form of standard python lists and returns the L2
loss according to the above formula.

In [213]:
def calculateL1Loss (vector1, vector2):
    loss = 0
    for i in range(len(vector1)):
        ls = vector1[i] - vector2[i]
        loss = loss + (ls**2)
    return loss/len(vector1)

vector1 = [random.randint(0, 100) for _ in range(10)]
vector2 = [random.randint(0, 100) for _ in range(10)]

print(vector1)
print(vector2)

print(f"Loss is: {calculateL1Loss(vector1, vector2)}")

[59, 77, 49, 66, 87, 89, 88, 21, 75, 32]
[95, 10, 25, 85, 39, 63, 64, 51, 75, 62]
Loss is: 1207.8


d) Now create another function that returns L2 loss but uses NumPy arrays instead of standard
python list. Compare the two approaches

In [218]:
def calculateL1Loss (vector1, vector2):
    loss = 0
    for i in range(len(vector1)):
        ls = vector1[i] - vector2[i]
        loss = loss + (ls**2)
    return loss/len(vector1)

vector1 = np.random.randint(0, 100, 10)
vector2 = np.random.randint(0, 100, 10)

print(vector1)
print(vector2)

print(f"Loss is: {calculateL1Loss(vector1, vector2)}")

[95 67 46  5 92 45  2 79 96 83]
[12 48 29  0 40 94 89  6 45  8]
Loss is: 3379.3


8:  Perform Matrix and Matrix Addition:

a) Create a function that performs matrix and matrix addition by using standard python data
structures only

In [241]:
def matrixAddition (matrix1, matrix2):
    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        return print("Invalde matrix for multiplication")
    
    numberOfRows = len(matrix1)
    numberOfColumns = len(matrix1[0])

    # print(numberOfRows, numberOfColumns)

    resultantMatrix = [[0 for _ in range(numberOfColumns)] for _ in range(numberOfRows)]

    # print(resultantMatrix)

    for i in range(numberOfRows):
        for j in range(numberOfColumns):
            resultantMatrix[i][j] = matrix1[i][j] + matrix2[i][j]

    return resultantMatrix

    # print(numberOfRows, numberOfColumns)

In [243]:
matrix1 = [[1,7,3], [2,5,11], [4,1,8]]
matrix2 = [[2,8,1], [1,1,4], [4,2,9]]

finalMatrix = matrixAddition(matrix1, matrix2)

for row in finalMatrix:
    print(row)

[3, 15, 4]
[3, 6, 15]
[8, 3, 17]


b) Create a function that performs matrix and matrix addition by using NumPy arrays.

In [248]:
matrix1 = np.random.randint(0, 10, 9).reshape(3,3)
matrix2 = np.random.randint(0, 10, 9).reshape(3,3)

print(matrix1, '\n')
print(matrix2,'\n')

result = matrix1 + matrix2

print(result)


[[4 8 1]
 [1 6 0]
 [5 1 5]] 

[[0 7 7]
 [8 7 2]
 [9 6 8]] 

[[ 4 15  8]
 [ 9 13  2]
 [14  7 13]]


9: Perform Matrix and Vector Multiplication

c) Create a function that performs matrix and vector multiplication by using standard python data
structures only

In [270]:
def multiplication (matrix, vector):

    if len(matrix) != len(vector):
        raise "Go back, not possible"

    numberOfRows = len(matrix)
    numberOfColumns = len(vector)

    nullMatrix = [[0 for _ in range(numberOfColumns)] for _ in range(numberOfRows)]

    for i in range(numberOfColumns):
        for j in range(numberOfRows):
            nullMatrix[i][j] = matrix[i][j] * vector[j]

    return nullMatrix


In [272]:
matrix = [[1,7,3], 
          [2,5,11],
          [4,1,8]]
vector = [2,8,1]


result = multiplication (matrix, vector)
for row in result:
    print(row)

[2, 56, 3]
[4, 40, 11]
[8, 8, 8]


d) Create a function that performs matrix and vector multiplication by using NumPy arrays.

In [277]:
matrix1 = np.random.randint(0, 10, 9).reshape(3,3)
vector = np.random.randint(0, 10, 3).reshape(3,1)

print(matrix1)
print(vector)

result = np.dot(matrix, vector)

print(result)


[[2 8 6]
 [2 0 5]
 [9 1 5]]
[[5]
 [5]
 [9]]
[[ 67]
 [134]
 [ 97]]


10: Perform Matrix and Matrix Multiplication:

e) Create a function that performs matrix and matrix multiplication by using standard python data
structures only.

In [278]:
def multiplication (matrix1, matrix2):

    if len(matrix1) != len(matrix2) or len(matrix1[0]) != len(matrix2[0]):
        raise "Go back, not possible"

    numberOfRows = len(matrix1)
    numberOfColumns = len(matrix2)

    nullMatrix = [[0 for _ in range(numberOfColumns)] for _ in range(numberOfRows)]

    for i in range(numberOfColumns):
        for j in range(numberOfRows):
            nullMatrix[i][j] = matrix1[i][j] * matrix2[i][j]

    return nullMatrix


In [280]:
matrix1 = [[1,7,3], [2,5,11], [4,1,8]]
matrix2 = [[2,1,4], [9,3,6], [2,8,1]]

for row in matrix1:
    print(row)
print('\n')
for row in matrix2:
    print(row)
print('\n')


result = multiplication (matrix1, matrix2)
for row in result:
    print(row)

[1, 7, 3]
[2, 5, 11]
[4, 1, 8]


[2, 1, 4]
[9, 3, 6]
[2, 8, 1]


[2, 7, 12]
[18, 15, 66]
[8, 8, 8]


f) Create a function that performs matrix and matrix multiplication by using NumPy arrays.

In [282]:
matrix1 = np.random.randint(0, 10, 9).reshape(3,3)
matrix2 = np.random.randint(0, 10, 9).reshape(3,3)

print(matrix1)
print('\n')
print(matrix2)
print('\n')

result = np.dot(matrix1, matrix2)

print(result)


[[4 3 6]
 [2 1 4]
 [7 0 9]]


[[0 7 8]
 [4 5 1]
 [7 1 1]]


[[54 49 41]
 [32 23 21]
 [63 58 65]]


11:  Finding RREF of a Matrix

Create a function that takes a matrix as input and returns its RREF. Try both standard python and
numpy approach.

In [356]:
def rref (matrix):
    if len(matrix) == 0:
        raise "Empty matrix"

    for row in matrix:
        print(row)
    print('\n')
    
    steps = []

    if matrix[0][0] == 0:

        if matrix[1][0] != 0:
            matrix[0], matrix[1] = matrix[1], matrix[0]
            for row in matrix:
                print(row)
            print('\n')
            

        elif matrix[2][0] != 0:
            matrix[0], matrix[1] = matrix[1], matrix[0]
            for row in matrix:
                print(row)
            print('\n')
            message = 'R1 is replaced with R3'
            steps.append(message)
        else:
            for row in matrix:
                print(row)
            print('\n')
            return print("Matrix has 0 in its first column")

        
    cofR1 = matrix[0][0]
    noOfRows = len(matrix)
    noOfColumns = len(matrix[0])
    
    for i in range(noOfRows):
        matrix[0][i] = matrix[0][i]/cofR1

    for row in matrix:
        print(row)
    print('\n')
    
    if matrix[1][0] != 0:
        cofR2 = matrix[1][0]
        for i in range(noOfRows):
            matrix[1][i] = matrix[1][i]-(cofR2*matrix[0][i])
    
    for row in matrix:
        print(row)
    print('\n')

    if matrix[2][0] != 0:
        cofR3 = matrix[2][0]
        for i in range(noOfRows):
            matrix[2][i] = matrix[2][i]-(cofR3*matrix[0][i])

    for row in matrix:
        print(row)
    print('\n')

    if matrix[1][1] != 1:
        cofR11 = matrix[1][1]
        for i in range(noOfRows):
            matrix[1][i] = matrix[1][i]/cofR11

        message = 'R1 is replaced with R2'
        steps.append(message)

    for row in matrix:
        print(row)
    print('\n')
    
    if matrix[2][1] != 0:
        cofR21 = matrix[2][1]
        cofR11 = matrix[1][1]

        for i in range(noOfRows):
            matrix[2][i] = (cofR11*matrix[2][i])-(cofR21*matrix[1][i])

    for row in matrix:
        print(row)
    print('\n')

    if matrix[2][2] != 1:
        cofR22 = matrix[2][2]
        for i in range(noOfRows):
            matrix[2][i] = matrix[2][i]/(cofR22)


    return (matrix)


matrix = [[0,2,3], [4,5,6], [7,8,9]]
for i in rref(matrix):
    print(i)


[0, 2, 3]
[4, 5, 6]
[7, 8, 9]


[4, 5, 6]
[0, 2, 3]
[7, 8, 9]


[1.0, 1.25, 1.5]
[0, 2, 3]
[7, 8, 9]


[1.0, 1.25, 1.5]
[0, 2, 3]
[7, 8, 9]


[1.0, 1.25, 1.5]
[0, 2, 3]
[0.0, -0.75, -1.5]


[1.0, 1.25, 1.5]
[0.0, 1.0, 1.5]
[0.0, -0.75, -1.5]


[1.0, 1.25, 1.5]
[0.0, 1.0, 1.5]
[0.0, 0.0, -0.375]


[1.0, 1.25, 1.5]
[0.0, 1.0, 1.5]
[-0.0, -0.0, 1.0]


In [380]:
matrix = np.random.randint(1,10,9).reshape(3,3)
result = sympy.Matrix(matrix).rref()

# for row in result:
#     print(row)

print(result)
print(result[0])
for row in result[0]:
    print(row)


(Matrix([
[1, 0, 0],
[0, 1, 0],
[0, 0, 1]]), (0, 1, 2))
Matrix([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
1
0
0
0
1
0
0
0
1


12: Solving a System of Linear Equations

Create a function that takes a matrix A and a vector b as input and returns the exact solution of the
following equation:
𝑨𝒙 = 𝒃
Try both standard python and numpy approach.

In [382]:
matrix = np.random.randint(1,10,12).reshape(3,4)
result = sympy.Matrix(matrix).rref()
print(result)

(Matrix([
[1, 0, 0,   4/7],
[0, 1, 0,  25/7],
[0, 0, 1, -27/7]]), (0, 1, 2))


13:  Finding Eigenvalues and Eigenvectors:

a) Create a function that takes a matrix as input and returns its eigenvalues. Try both standard
python and numpy approach.

In [391]:
matrix = np.random.randint(1,10,9).reshape(3,3)
print(matrix, '\n')

eigenValues= np.linalg.eigvals(matrix)
print(eigenValues)

[[8 9 7]
 [8 1 6]
 [3 6 7]] 

[18.38820904  2.74429598 -5.13250502]


b) Create a function that takes a matrix as input and returns its eigenvectors. Try both standard
python and numpy approach.

In [407]:
matrix = np.random.randint(1,10,9).reshape(3,3)
print(matrix, '\n')

eigenValues = np.linalg.eig(matrix)
print(eigenValues[1])

[[9 9 9]
 [2 6 3]
 [3 1 6]] 

[[ 0.89762439  0.67942432 -0.61885275]
 [ 0.29920813  0.22647477 -0.30942637]
 [ 0.32364326 -0.69791961  0.72199487]]


14:  Diagonalizing a Matrix:

Create a function that takes a matrix A as input and returns the matrices D and P according to the
following equation:
𝐴 = 𝑃𝐷𝑃−1
Where D is a diagonal matrix of eigenvalues of A and P is a matrix containing the corresponding
eigenvectors in its columns. Try both standard python and numpy approach.

In [414]:
matrix = np.random.randint(1,10,9).reshape(3,3)
print(matrix, '\n')

eigenValues, eigenVectors = np.linalg.eig(matrix)
diagonal = np.diag(matrix)
diagonalMatrix = np.diag(eigenValues)
print(f'{eigenValues} \n\n {eigenVectors}\n\n {diagonal}\n\n,{diagonalMatrix}' )

[[5 4 1]
 [4 5 4]
 [6 5 8]] 

[13.71476601  2.744106    1.54112799] 

 [[-0.3269393  -0.75296276  0.76279427]
 [-0.51404715  0.27521366 -0.598228  ]
 [-0.79301086  0.59774955 -0.24549575]]

 [5 5 8]

,[[13.71476601  0.          0.        ]
 [ 0.          2.744106    0.        ]
 [ 0.          0.          1.54112799]]


15: Finding SVD of a Matrix:

Create a function that takes a matrix A as input and returns its SVD. Try both standard python and
numpy approach.

In [422]:
matrix = np.random.randint(1,10,9).reshape(3,3)
print(matrix, '\n')

s, v, d = np.linalg.svd(matrix)
print(f'{s}\n\n{v}\n\n{d}')


[[5 7 7]
 [2 3 8]
 [7 5 3]] 

[[-0.69281453 -0.01372481 -0.7209852 ]
 [-0.49690565 -0.71546882  0.49111012]
 [-0.52258282  0.69850984  0.48886726]]

[15.93860567  5.18894908  1.42676443]

[[-0.50920161 -0.56173877 -0.65204545]
 [ 0.65331287  0.24090988 -0.71773583]
 [ 0.56026424 -0.79146193  0.24431947]]
